In [135]:
#Loading the dataset
import pandas as pd
dataset=pd.read_csv('California_House_Prediction.csv')
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [136]:
#Finding the Missing Values
dataset.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

In [137]:
#filling the null values with mean of the column
mean=dataset['total_bedrooms'].mean()
dataset['total_bedrooms'].fillna(value=mean, inplace=True)
dataset.isnull().sum()


longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
median_house_value    0
dtype: int64

In [138]:
#Converting Categorical Data Into Numerical Data
dataset['ocean_proximity'].replace(['NEAR BAY','<1H OCEAN','INLAND','ISLAND','NEAR OCEAN'],[0,1,2,3,4],inplace=True)

In [139]:
dataset

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         1627           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income  ocean_proximity  \
0             322         126         8.3252                0   
1            2401        1138         8.3014                0   
2             496         177         7.2574                0   
3             558         219         5.6431                0   
4             565         259         3.8462                0   
...           ...         ...            ...              ...   
20635         845         330         1.5603                2   
20636         356         114         2.5568                2   
20637        1007         433         1.7000                2   
20638         741         349         1.8672                2   
20639        1387         530         2.3886                2   

       median_house_value  
0                  452600  
1                  358500  
2                  352100  
3                  341300  
4                  342200  
...                   ...  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400  

[20640 rows x 10 columns]

In [140]:
#Extracting the X and Y values
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:, [-1]].values
print(x)

[[-122.23     37.88     41.     ...  126.        8.3252    0.    ]
 [-122.22     37.86     21.     ... 1138.        8.3014    0.    ]
 [-122.24     37.85     52.     ...  177.        7.2574    0.    ]
 ...
 [-121.22     39.43     17.     ...  433.        1.7       2.    ]
 [-121.32     39.43     18.     ...  349.        1.8672    2.    ]
 [-121.24     39.37     16.     ...  530.        2.3886    2.    ]]


In [141]:
print(y)

[[452600]
 [358500]
 [352100]
 ...
 [ 92300]
 [ 84700]
 [ 89400]]


In [142]:
#Splitting the data into training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [143]:
#Standardization
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
scaler.fit(X_train)
X_train_std=scaler.transform(X_train)
X_test_std=scaler.transform(X_test)

In [144]:
#Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor
regres=DecisionTreeRegressor(random_state=0)
regres.fit(X_train_std,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [145]:
#making predictions
y_pred=regres.predict(X_test_std)
result=pd.DataFrame({'Actual':[y_test]*20640, 'Predicted':[y_pred]*20640})
result.head()

Actual  \
0  [[236900], [153700], [204200], [196400], [1116...   
1  [[236900], [153700], [204200], [196400], [1116...   
2  [[236900], [153700], [204200], [196400], [1116...   
3  [[236900], [153700], [204200], [196400], [1116...   
4  [[236900], [153700], [204200], [196400], [1116...   

                                           Predicted  
0  [288200.0, 197500.0, 215100.0, 166700.0, 95600...  
1  [288200.0, 197500.0, 215100.0, 166700.0, 95600...  
2  [288200.0, 197500.0, 215100.0, 166700.0, 95600...  
3  [288200.0, 197500.0, 215100.0, 166700.0, 95600...  
4  [288200.0, 197500.0, 215100.0, 166700.0, 95600...

In [146]:
#Finding Root Mean Square Error
import numpy as np
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))
#root mean error
print(np.sqrt(mean_squared_error(y_test,y_pred))) 

5038526812.495882
70982.5810498314


In [147]:
#making predictions by taking a sample 
import numpy as np
arr=np.array([[-122.23,37.88,41,880,129,322,126,8.3252,0]])
y_pr=regres.predict(arr)
y_pr

array([242000.])

In [148]:
#Random Forest Regression
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,random_state=0)
regressor.fit(X_train_std,y_train)

C:\Users\snehalatha\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [149]:
#making predictions
y_pred=regressor.predict(X_test_std)
result=pd.DataFrame({'Actual':[y_test]*20640, 'Predicted':[y_pred]*20640})
result.head()

Actual  \
0  [[236900], [153700], [204200], [196400], [1116...   
1  [[236900], [153700], [204200], [196400], [1116...   
2  [[236900], [153700], [204200], [196400], [1116...   
3  [[236900], [153700], [204200], [196400], [1116...   
4  [[236900], [153700], [204200], [196400], [1116...   

                                           Predicted  
0  [268644.0, 179141.0, 171266.0, 206940.01, 1466...  
1  [268644.0, 179141.0, 171266.0, 206940.01, 1466...  
2  [268644.0, 179141.0, 171266.0, 206940.01, 1466...  
3  [268644.0, 179141.0, 171266.0, 206940.01, 1466...  
4  [268644.0, 179141.0, 171266.0, 206940.01, 1466...

In [150]:
#Finding Root Mean Square Error
import numpy as np
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))
#root mean error
print(np.sqrt(mean_squared_error(y_test,y_pred))) 

2315391093.3387904
48118.51092187694


In [151]:
#making predictions by taking a sample 
import numpy as np
arr=np.array([[-122.22,37.86,21,7099,1106,2401,1138,8.3014,0]])
y_pred=regressor.predict(arr)
y_pred

array([371761.35])